// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// Support multiple formats + hardcoded fallback to ensure site always works
const SUPABASE_URL = 
  import.meta.env.VITE_SUPABASE_URL || 
  import.meta.env.vitesupabaseurl ||
  import.meta.env.VITESUPABASEURL ||
  (import.meta.env as any).vite_supabase_url ||
  'https://yiorietrtfosjnpzznnr.supabase.co'; // Hardcoded fallback - ensures site works
  
const SUPABASE_PUBLISHABLE_KEY = 
  import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY || 
  import.meta.env.vitepublishiblekey ||
  import.meta.env.VITESUPABASEPUBLISHABLEKEY ||
  (import.meta.env as any).vite_supabase_publishable_key ||
  'sb_publishable_imsM3rmYQD2Oq8Ip-CtVag_w8BNiYeQ'; // Hardcoded fallback - ensures site works

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});